spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/timeline?chracterEncoding=utf-8
    username: root
    password: v09809809800
  jpa:
    hibernate:
      ddl-auto: update #先用创建模式，根据定义的实体类来建表
    show-sql: true
  thymeleaf: #thymeleaf静态资源配置
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5
      encoding: UTF-8
      servlet:
        content-type:
          text/html
      cache: false #项目上线的时候一定是True
